### ISSUE TITLE
only dark theme in IOS version?

### ISSUE THREAD

**Issue by AndyIreland** [FredLeudon/iOS-CanZE#1]
hello is there only a dark theme when using on Ipad IOS ? - I went into settings and could not find a setting to change to a light theme
Thanks.

![297578806_459870299321336_2059404100162868535_n](https://user-images.githubusercontent.com/49172217/183256571-41955893-221c-4946-852c-2477102cfefb.jpg)

**Comment by FredLeudon** [comment]
Sorry, there is only a dark theme on this version.

This build is discontinued since July 2019.

i recommend to use the official version of CanZE developed by the team.

**Comment by AndyIreland** [comment]
thank you
